server:
  # 服务器的HTTP端口，默认为80
  port: 6666
  servlet:
    # 应用的访问路径
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    lazyLoadingEnabled: true #延时加载的开关
    jdbcTypeForNull: null
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

spring:
  application:
    name: ric-teng
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 220MB
      max-request-size: 220MB
  mvc:
    async:
      request-timeout: 20000

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    redis:
      enabled: false
  enabled-by-default: false
